version: '3.9'

services:
  apigateway-postgres: 
    image: postgres:16 
    container_name: apigateway-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: apigateway_service
      POSTGRES_PASSWORD: generated_password_for_fun
    volumes:
      - apigateway_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apigateway_service -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  apigateway-redis:
    image: redis:7
    container_name: apigateway-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - apigateway_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  cathay-apigateway-ojt:
    image: apigateway:latest
    container_name: cathay-apigateway-ojt
    ports:
      - "8080:8080" # Map port 8080 của máy thật vào 8080 của container

volumes:
  apigateway_pg_data:
  apigateway_redis_data: