version: '3.9'

services:
  # apigateway-postgres:
  #   image: postgres:17
  #   container_name: apigateway-postgres
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: apigateway_service
  #     POSTGRES_PASSWORD: generated_password_for_fun
  #   volumes:
  #     - apigateway_pg_data:/var/lib/postgresql/data
  #     - ./sql-script.sql:/docker-entrypoint-initdb.d/sql-script.sql:ro
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U apigateway_service -d postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5


  apigateway-server:
    build:
      context: ./apps/apigateway
    image: apigateway:v1
    container_name: apigateway-server
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Ho_Chi_Minh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  # ── identity ────────────────────────────────────────
  identity-postgres:
    image: postgres:17
    container_name: identity-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: identity_service
      POSTGRES_PASSWORD: generated_password_for_fun
    volumes:
      - identity_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U identity_service -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  identify-service:
    build:
      context: ./apps/identify-service
    image: identify-service:v1
    container_name: identify-service
    ports:
      - "8081:8081"
    depends_on:
      identity-postgres:
        condition: service_healthy
    environment:
      TZ: Asia/Ho_Chi_Minh

  # ── order ───────────────────────────────────────────
  order-postgres:
    image: postgres:17
    container_name: order-postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: order_service
      POSTGRES_PASSWORD: generated_password_for_fun
    volumes:
      - order_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_service -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: ./apps/order-service
    image: order-service:v1
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      order-postgres:
        condition: service_healthy
    environment:
      TZ: Asia/Ho_Chi_Minh

volumes:
  apigateway_pg_data:
  apigateway_redis_data:
  identity_pg_data:
  order_pg_data:
